### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by Arnav2001** [Bahmni/connect2Bahmni#11]
@angshu I have submitted my proposal for Code for GovTech (C4GT) kindly review my proposal as I want to work on this project and I would like to start from login page UI . I have successfully setup docker and this app on my laptop. I want some suggestions from your side that do you want me to include animations as well or keep UI simple without any animation. After this implementation I would work with features of application as well. Kindly guide me with your advice so that I can proceed.

**Comment by angshu** [comment]
closing this issue, as the C4GT program related issues were picked up by another contributor. if you are interested to work on other areas, please ping us on slack
