### ISSUE TITLE
Migration to latest version of Gradle

### ISSUE THREAD

**Issue by Arnav2001** [Bahmni/connect2Bahmni#9]
While running this project I have faced java and gradle incompatibility issue. I would suggest to upgrade gradle version to latest version so that we can use more features which have been added in latest patch.

**Comment by Arnav2001** [comment]
@angshu please assign me this issue.

**Comment by angshu** [comment]
Thank you. Just raise a PR.

**Comment by Arnav2001** [comment]
@angshu Can you please tell me what version of flutter and java is used to build this project. So that I can look for the changes which I need to do

**Comment by Arnav2001** [comment]
Hi @angshu,
I have opened a pull request. Let me know if this way is correct and if there is any changes required after this I want to work on UI part of Login Page because it looks very basic. I can add animated login page if you want. Let me know about this idea.

**Comment by Arnav2001** [comment]
@angshu I have seen that you require Proguard for jitsu meet so I will revert my pull request and then I will push gradle changes only.

**Comment by Arnav2001** [comment]
closing this issue because proguard cannot work with current gradle version I believe. Correct me if I am wrong love to learn more.
